### ISSUE TITLE
typo ultmtcdrt

### ISSUE THREAD

**Issue by mpschernie** [AbcAeffchen/SepaUtilities#5]
Hi,
seems like there is typo in the ultimate creditor field name in some places, it's written as "ultmtcd**rt**" instead of "ultmtcd**tr**". This especially breaks the sanitizing feature when using it with the Sephpa library.

**Comment by AbcAeffchen** [comment]
Thanks. for reporting this.

I fixed this issue and tag a new version soon. Sephpa will also get an update to require the new version.
